"""
Django settings for mileslib_api project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from mileslib import StaticMethods as sm

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$%&r&_r($8hj_4f+okr4tdg#o27hvby2a-sh3og&#af46w&(-k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_auth_adfs',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mileslib_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mileslib_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

#SECRET_KEY = sm.cfg_get("SECRET_KEY", default="changeme")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": sm.cfg_get("POSTGRES_DB", default="mydb"),
        "USER": sm.cfg_get("POSTGRES_USER", default="postgres"),
        "PASSWORD": sm.cfg_get("POSTGRES_PASSWORD", default="changeme"),
        "HOST": sm.cfg_get("POSTGRES_HOST", default="localhost"),
        "PORT": sm.cfg_get("POSTGRES_PORT", default="5432"),
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#Azure AD Authenticiation
AUTHENTICATION_BACKENDS = [
    'django_auth_adfs.backend.AdfsAuthCodeBackend',
    'django.contrib.auth.backends.ModelBackend',
]

AUTH_ADFS = {
    "AUDIENCE": sm.cfg_get("DJANGO_CLIENT_ID", default="changeme"),
    "CLIENT_ID": sm.cfg_get("DJANGO_CLIENT_ID", default="changeme"),
    "CLIENT_SECRET": sm.cfg_get("DJANGO_CLIENT_SECRET", default="changeme"),
    "TENANT_ID": sm.cfg_get("DJANGO_TENANT_ID", default="changeme"),
    "RELYING_PARTY_ID": sm.cfg_get("DJANGO_CLIENT_ID", default="changeme"),
    "REDIR_URI": sm.cfg_get("DJANGO_REDIRECT_URI", default="http://localhost:8000/oauth2/callback"),
    "LOGIN_REDIRECT_URL": "/",
    "USERNAME_CLAIM": "upn",
}


LOGIN_URL = "/oauth2/login/"
LOGOUT_REDIRECT_URL = "https://login.microsoftonline.com/common/oauth2/logout"